In [1]:
import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
##Final data with team network stats
df = pd.read_csv('./data/final_networked_by_team.csv')

In [3]:
df[['Pos', 'College','team','Draft_Team']] = df[['Pos', 'College','team','Draft_Team']].fillna(value="")
df[['Draft_Round', 'Draft_Pick','Draft_Year','crimeCount','No','GS']] = df[['Draft_Round', 'Draft_Pick','Draft_Year','crimeCount','No','GS']].fillna(value=0)

avgAge = math.floor(df['Age'].mean())
avgHt = math.floor(df['Ht'].mean())
avgWt = math.floor(df['Wt'].mean())
avgBD = math.floor(df['BirthDate'].mean())
df['Age'] = df['Age'].fillna(value=avgAge)
df['Ht'] = df['Ht'].fillna(value=avgHt)
df['Wt'] = df['Wt'].fillna(value=avgWt)
df['BirthDate'] = df['BirthDate'].fillna(value=avgBD)

In [4]:
#df.head()
df[['Pos', 'College','team','Draft_Team']].sample()

Pos        College team         Draft_Team
26007  SS  Virginia Tech  SEA  Seattle Seahawks

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33282 entries, 0 to 33281
Data columns (total 38 columns):
No                       33282 non-null float64
name                     33282 non-null object
Age                      33282 non-null float64
Pos                      33282 non-null object
G                        33282 non-null float64
GS                       33282 non-null float64
Wt                       33282 non-null float64
Ht                       33282 non-null float64
College                  33282 non-null object
BirthDate                33282 non-null float64
Yrs                      33282 non-null int64
AV                       33281 non-null float64
team                     33282 non-null object
year                     33282 non-null float64
Draft_Team               33282 non-null object
Draft_Round              33282 non-null float64
Draft_Pick               33282 non-null float64
Draft_Year               33282 non-null float64
crimeCount               33282 non

In [6]:
df.describe()

No           Age             G            GS            Wt  \
count  33282.000000  33282.000000  33282.000000  33282.000000  33282.000000   
mean      52.814584     26.646806     11.523286      5.751337    243.628268   
std       29.055944      3.399155      5.163789      6.310930     45.076659   
min        0.000000     20.000000      1.000000      0.000000    150.000000   
25%       27.000000     24.000000      7.000000      0.000000    205.000000   
50%       54.000000     26.000000     14.000000      3.000000    236.000000   
75%       80.000000     29.000000     16.000000     12.000000    281.000000   
max       99.000000     47.000000     16.000000     16.000000    376.000000   

                 Ht      BirthDate           Yrs            AV          year  \
count  33282.000000   33282.000000  33282.000000  33281.000000  33282.000000   
mean      74.004507  724114.593474      3.551499      3.370121   2008.205186   
std        0.392354    4296.345344      3.302294      3.601035      4.879879   
min       66.000000  718800.000000     -3.000000     -5.000000   2000.000000   
25%       74.000000  722042.000000      1.000000      1.000000   2004.000000   
50%       74.000000  723690.000000      3.000000      2.000000   2008.000000   
75%       74.000000  725446.000000      5.000000      6.000000   2012.000000   
max       80.000000  755320.000000     25.000000     26.000000   2016.000000   

           ...       Disorderly conduct         Sex  Theft / Burglary  \
count      ...               679.000000  679.000000        679.000000   
mean       ...                 0.051546    0.026510          0.027982   
std        ...                 0.221272    0.160763          0.173751   
min        ...                 0.000000    0.000000          0.000000   
25%        ...                 0.000000    0.000000          0.000000   
50%        ...                 0.000000    0.000000          0.000000   
75%        ...                 0.000000    0.000000          0.000000   
max        ...                 1.000000    1.000000          2.000000   

       Murder / Manslaughter  Animal Abuse  Team_Degrees  Team_Closeness  \
count             679.000000    679.000000  33282.000000    33282.000000   
mean                0.008837      0.008837     36.281233        0.364585   
std                 0.093656      0.093656      7.881125        0.009935   
min                 0.000000      0.000000     21.000000        0.341232   
25%                 0.000000      0.000000     31.000000        0.358655   
50%                 0.000000      0.000000     37.000000        0.365947   
75%                 0.000000      0.000000     41.000000        0.370656   
max                 1.000000      1.000000     50.000000        0.382979   

       Team_Betweenness  player_Degrees  player_Eigen  
count      33282.000000    33282.000000  33282.000000  
mean           0.055353      983.394658      0.012325  
std            0.016987      506.647746      0.006349  
min            0.022637      327.000000      0.003090  
25%            0.042566      482.000000      0.006350  
50%            0.056650      883.000000      0.011299  
75%            0.070111     1290.000000      0.016396  
max            0.085786     3528.000000      0.040974  

[8 rows x 33 columns]

In [7]:
##Handling categorical data
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

pos = df['Pos']
le.fit(pos)
po = le.transform(pos)
df['Pos'] = po

col = df['College']
le.fit(col)
co = le.transform(col)
df['College'] = co

team = df['team']
le.fit(team)
te = le.transform(team)
df['team'] = te

dteam = df['Draft_Team']
le.fit(dteam)
dte = le.transform(dteam)
df['Draft_Team'] = dte



In [8]:
df.to_csv('data/final_encoded.csv')

In [9]:
dropList = ['name','crimeCount','DUI','Other','Drugs','Domestic Violence','Resisting','Assault / Battery','Gun','Alcohol','License / Traffic','Disorderly conduct','Sex','Theft / Burglary','Murder / Manslaughter','Animal Abuse','AV']

X = df.drop(dropList, axis=1)
y = df['crimeCount']

X.isnull().any()
#set(y.isnull())



No                  False
Age                 False
Pos                 False
G                   False
GS                  False
Wt                  False
Ht                  False
College             False
BirthDate           False
Yrs                 False
team                False
year                False
Draft_Team          False
Draft_Round         False
Draft_Pick          False
Draft_Year          False
Team_Degrees        False
Team_Closeness      False
Team_Betweenness    False
player_Degrees      False
player_Eigen        False
dtype: bool

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 22)

In [11]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 300)
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [12]:
rfc_pred = rfc.predict(X_test)


In [13]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, rfc_pred))

             precision    recall  f1-score   support

        0.0       0.98      1.00      0.99     13050
        1.0       0.79      0.18      0.29       249
        2.0       0.00      0.00      0.00        14
        3.0       0.00      0.00      0.00         0

avg / total       0.98      0.98      0.98     13313



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [14]:
print(confusion_matrix(y_test, rfc_pred))

[[13040    10     0     0]
 [  204    44     0     1]
 [   12     2     0     0]
 [    0     0     0     0]]
